import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/css/filament/**/*.css',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                grotesk: ['Space Grotesk', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                // Neo-Brutalism Tech Design System
                'nb-surface': '#FDFCF6',
                'nb-bg': '#f9f9ff',
                'nb-primary': '#0058be',
                'nb-primary-cont': '#2170e4',
                'nb-on-primary': '#ffffff',
                'nb-secondary': '#fed01b',
                'nb-on-secondary': '#6f5900',
                'nb-success': '#10B981',
                'nb-danger': '#EF4444',
                'nb-stroke': '#000000',
                'nb-on-surface': '#191b23',
                'nb-muted': '#424754',
                'nb-outline': '#727785',
                'nb-card': '#ffffff',
                'nb-low': '#f2f3fd',
                'nb-container': '#ecedf7',
                'nb-high': '#e6e7f2',
                'nb-highest': '#e1e2ec',
                'nb-yellow-fixed': '#ffe083',
                'nb-tertiary-fixed': '#ffdcc6',
                // Keep Stitch token names for compatibility
                'surface': '#FDFCF6',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f2f3fd',
                'surface-container': '#ecedf7',
                'surface-container-high': '#e6e7f2',
                'surface-container-highest': '#e1e2ec',
                'surface-variant': '#e1e2ec',
                'surface-bright': '#f9f9ff',
                'on-surface': '#191b23',
                'on-surface-variant': '#424754',
                'primary': '#0058be',
                'on-primary': '#ffffff',
                'primary-container': '#2170e4',
                'on-primary-container': '#fefcff',
                'primary-fixed': '#d8e2ff',
                'secondary-container': '#fed01b',
                'on-secondary-container': '#6f5900',
                'secondary-fixed': '#ffe083',
                'tertiary-fixed': '#ffdcc6',
                'on-tertiary-fixed': '#311400',
                'on-tertiary-container': '#fffbff',
                'tertiary-container': '#b75b00',
                'outline': '#727785',
                'outline-variant': '#c2c6d6',
                'stroke': '#000000',
                'success': '#10B981',
                'danger': '#EF4444',
                'inverse-surface': '#2e3038',
                'surface-tint': '#005ac2',
            },
            boxShadow: {
                'neo': '6px 6px 0px 0px #000000',
                'neo-sm': '3px 3px 0px 0px #000000',
                'neo-xs': '2px 2px 0px 0px #000000',
            },
            borderWidth: {
                '3': '3px',
            },
            spacing: {
                'gutter': '16px',
                'margin-desktop': '32px',
                'margin-mobile': '16px',
                'shadow-offset': '6px',
                'stroke-width': '3px',
            },
            fontSize: {
                'headline-xl': ['48px', { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.02em' }],
                'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.01em' }],
                'headline-lg-mob': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
                'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
                'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '1.2', fontWeight: '600' }],
            },
        },
    },

    plugins: [forms],
};
